#!/bin/sh

if [ -z "$1" ]
then
  echo "Usage: `basename $0` github-user-name"
  exit 1
fi

gh-auth add --users=$1
echo "Copying keys to friend user"
mkdir -p /home/friend/.ssh
sudo cp ~/.ssh/authorized_keys /home/friend/.ssh/authorized_keys
sudo chown -R friend:friend /home/friend/.ssh
gh-auth remove --users=$1

echo "To end your friend's session, use \"bye\""
